name: Check PR Merged and Insert Analysis Results

on:
  pull_request:
    types: [closed]

jobs:
  check-pr-merged:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary jq

    - name: Insert analysis results into PostgreSQL
      env:
        PGHOST: ${{ secrets.PGHOST }}
        PGPORT: ${{ secrets.PGPORT }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
      run: |
        echo "Inserting analysis results into PostgreSQL..."
        file_type=$(file -b --mime-type results.json)
        if [ "$file_type" == "application/json" ]; then
          STATUS=$(jq -r '.projectStatus.status' results.json)
          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            MERGE_STATUS="accepted"
          else
            MERGE_STATUS="rejected"
          fi
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Branch: ${{ github.head_ref }}"
          echo "Status: $STATUS"
          echo "Merge Status: $MERGE_STATUS"
          psql -c "INSERT INTO sonar_analysis_results (pr_number, branch, status, analysis_data, developer) VALUES ('${{ github.event.pull_request.number }}', '${{ github.head_ref }}', '$STATUS' , '$(cat results.json)', 'Mohit');"
        else
          echo "Skipping PostgreSQL insertion due to non-JSON response."
        fi
